name: Continous Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          # Recuperamos el secreto y lo guardamos en un identificador ssh que estamos creando
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          # Le damos permisos a este identificador
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Git config
        run: |
          git config --global user.email "cd-user@my-app-com"
          git config --global user.name "cd-user"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy -- -r git@github.com:Alienah/github-actions-demo.git

